FROM selenium/standalone-chrome

USER root

RUN apt update && apt install python3-pip -y
RUN pip install pytest selenium
# RUN mkdir /tests/
# WORKDIR /tests/
# ADD tests .
# RUN chmod +x wait-for-grid.sh

USER 1200

# https://stackoverflow.com/questions/53902507/unknown-error-session-deleted-because-of-page-crash-from-unknown-error-cannot
