[tool.black]
skip-string-normalization = true
line-length = 100
target-version = ['py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | notebooks
  | cdk.out
  | venv
)/
'''

[tool.isort]
# make it compatible with black
profile = "black" 
